language: node_js

node_js:
  - "10"

before_install:
  - "sh ./travis_credential_setup.sh"

install:
  - "npm install"
  - "pyenv global 3.6.3"
  - "pip install pip --upgrade"
  - "pip install awscli --upgrade --user"

script:
  - "npm run build"
  - "aws s3 sync ./build/ s3://mjfs.us --acl public-read --delete"
  - >
    aws cloudfront create-invalidation --distribution-id $CF_DISTRIBUTION_ID --paths
    /asset-manifest.json /favicon.ico /index.html /manifest.json /service-worker.js
