language: node_js

node_js:
  - "10"

before_install:
  - "sh ./travis_credential_setup.sh"

install:
  - "npm install"
  - "pip install awscli --user"

script:
  - "npm run build"

deploy:
  - "aws s3 sync ./build/ s3://mjfs.us --acl public-read --delete"

after_deploy:
  - >
    aws cloudfront create-invalidation --distribution-id $CF_DISTRIBUTION_ID --paths
    /asset-manifest.json /favicon.ico /index.html /manifest.json /service-worker.js
